### PR TITLE
Change file format to unix.

### PR DESCRIPTION
**Pull request by koos303**
I'm getting an error, due to the fact that the file is saved as a DOS file, in combination with some line endings. In this pull request I've changed it to the Unix file format to remove the errors listed below:

```
Error detected while processing /Users/case/.vim/bundle/bufexplorer.zip/plugin/bufexplorer.vim:
line   66:
E492: Not an editor command: ^M
line   69:
E15: Invalid expression: exists("g:bufexplorer_version") || &cp^M
line 1217:
E171: Missing :endif
line   66:
E492: Not an editor command: ^M
line   69:
E15: Invalid expression: exists("g:bufexplorer_version") || &cp^M
line 1217:
E171: Missing :endif
Press ENTER or type command to continue
```

### CODE REVIEW

**Comment by kamitchell** [comment]
:+1:

**Comment by chiphogg** [comment]
Yes, please fix.

**Comment by choffee** [comment]
Might be worth doing all the other files as well as they all seem to have been changed into windows format in the last commit. ^M everywhere!

**Comment by likan999** [comment]
:+1:

**Comment by menghan** [comment]
:+1:

**Comment by menghan** [comment]
@koos303  Jeff Lanzarotta fixed this problem in v7.4.6.

**Comment by koos303** [comment]
@menghan excellent, I will close this PR

**Pull request closed without merging**
